#!/usr/bin/env python3
"""Generate phy/ldpc_tables.h from the 38.212 base graph CSVs (Sionna format, see tables/NOTICE).

Usage: python3 phy/gen_tables.py phy/tables phy/ldpc_tables.h
Each CSV line after the two header lines is: row;col;V0;...;V7 with a blank row meaning
"same row as the line above". Output arrays list (row, col, shift[8]) sorted row-major.
"""
import os
import sys

# (file, symbol prefix, expected entries, rows, cols)
GRAPHS = [
    ("5G_bg1.csv", "BG1", 316, 46, 68),
    ("5G_bg2.csv", "BG2", 197, 42, 52),
]


def parse(path):
    """Return sorted list of (row, col, [8 shifts])."""
    entries = []
    row = None
    with open(path, newline="") as f:
        lines = f.read().splitlines()
    for ln, line in enumerate(lines[2:], start=3):
        if not line.strip():
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 10:
            raise ValueError(f"{path}:{ln}: expected 10 fields, got {len(parts)}")
        if parts[0] != "":
            row = int(parts[0])
        if row is None:
            raise ValueError(f"{path}:{ln}: first data line has no row index")
        col = int(parts[1])
        shifts = [int(p) for p in parts[2:10]]
        entries.append((row, col, shifts))
    entries.sort(key=lambda e: (e[0], e[1]))
    return entries


def check(entries, name, n_exp, rows, cols):
    assert len(entries) == n_exp, f"{name}: {len(entries)} entries, expected {n_exp}"
    assert len({(r, c) for r, c, _ in entries}) == n_exp, f"{name}: duplicate (row, col)"
    assert {r for r, _, _ in entries} == set(range(rows)), f"{name}: rows are not 0..{rows - 1}"
    assert max(c for _, c, _ in entries) == cols - 1, f"{name}: max column is not {cols - 1}"
    assert min(c for _, c, _ in entries) == 0, f"{name}: min column is not 0"
    for r, c, s in entries:
        assert all(0 <= v < 384 for v in s), f"{name}: shift out of range at ({r},{c})"


def emit(graphs):
    out = [
        "// Generated by phy/gen_tables.py from phy/tables/5G_bg{1,2}.csv (3GPP TS 38.212",
        "// Tables 5.3.2-2/-3, via NVIDIA Sionna, Apache-2.0; see phy/tables/NOTICE). Do not edit.",
        "// Entries are sorted row-major; shift[i] is V for lifting set index i (Table 5.3.2-1).",
        "#pragma once",
        "",
        "namespace sb {",
        "",
        "struct LdpcBaseEntry {",
        "    short row;",
        "    short col;",
        "    short shift[8];",
        "};",
        "",
    ]
    for name, entries, rows, cols in graphs:
        out.append(f"constexpr int k{name}Rows = {rows};")
        out.append(f"constexpr int k{name}Cols = {cols};")
        out.append(f"constexpr int k{name}Entries = {len(entries)};")
        out.append(f"constexpr LdpcBaseEntry k{name}[k{name}Entries] = {{")
        for r, c, s in entries:
            out.append(f"    {{{r}, {c}, {{{', '.join(str(v) for v in s)}}}}},")
        out.append("};")
        out.append("")
    out.append("}  // namespace sb")
    out.append("")
    return "\n".join(out)


def main(argv):
    if len(argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    graphs = []
    for fname, name, n_exp, rows, cols in GRAPHS:
        entries = parse(os.path.join(argv[1], fname))
        check(entries, name, n_exp, rows, cols)
        graphs.append((name, entries, rows, cols))
    with open(argv[2], "w") as f:
        f.write(emit(graphs))
    print(f"wrote {argv[2]}: " + ", ".join(f"{n} {len(e)} entries" for n, e, _, _ in graphs))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
